import type { ReportBuildInput } from "./shared"
import {
  allocateGwpByPhase,
  buildCoverStamp,
  detectSystemBoundary,
  escapeHtml,
  getBaselineGwp,
  sumPhaseKg,
  wrapReportHtml,
} from "./shared"

const STRINGS = {
  da: {
    title: "Produktets klimafodaftryk",
    subtitle: "Carbon footprint i overensstemmelse med ISO 14067:2018",
    generatedBy: "Genereret af LCA Compass",
    toc: "Indhold",
    s1: "Hvad denne rapport dækker",
    s2: "Afgrænsning og funktionel enhed",
    s3: "Deklareret klimaresultat (GWP)",
    s4: "Bidrag pr. livscyklusfase",
    s5: "Metode og datakvalitet",
    s6: "Forbehold",
    scopeBox:
      "Denne rapport rapporterer udelukkende drivhusgasemissioner (GWP100) for det angivne produkt. Den erstatter ikke en fuld LCA eller EPD.",
    notIncluded: "Ikke medtaget i denne rapport",
    notIncludedList:
      "Øvrige miljøpåvirkningskategorier (forsuring, eutrofiering, ressourceudtømning), fuldt LCI-inventar og social LCA.",
    declaredGwp: "Deklareret klimapåvirkning",
    perFu: "pr. funktionel enhed",
    phase: "Fase",
    share: "Andel",
    gwp: "GWP",
    method: "Beregningsmetode",
    boundary: "Systemgrænse",
    period: "Tidsperiode",
    dataQuality: "Datakvalitet",
    compliance: "ISO 14044 compliance (baggrunddata)",
  },
  en: {
    title: "Product Carbon Footprint",
    subtitle: "Carbon footprint in accordance with ISO 14067:2018",
    generatedBy: "Generated by LCA Compass",
    toc: "Contents",
    s1: "What this report covers",
    s2: "Scope and functional unit",
    s3: "Declared climate result (GWP)",
    s4: "Contribution by life cycle phase",
    s5: "Method and data quality",
    s6: "Disclaimers",
    scopeBox:
      "This report states greenhouse gas emissions (GWP100) for the stated product only. It does not replace a full LCA or EPD.",
    notIncluded: "Not included in this report",
    notIncludedList:
      "Other impact categories (acidification, eutrophication, resource depletion), full LCI inventory, and social LCA.",
    declaredGwp: "Declared climate impact",
    perFu: "per functional unit",
    phase: "Phase",
    share: "Share",
    gwp: "GWP",
    method: "Calculation method",
    boundary: "System boundary",
    period: "Time period",
    dataQuality: "Data quality",
    compliance: "ISO 14044 compliance (background data)",
  },
}

export function buildCarbonFootprint14067Report(input: ReportBuildInput): string {
  const { product, locale, date, reportId } = input
  const s = STRINGS[locale]
  const da = locale === "da"
  const gs = product.goalScope ?? {}
  const lcia = product.lcia ?? {}
  const interp = product.interpretation ?? {}
  const boundary = detectSystemBoundary(gs.systemBoundaries)
  const totalGwp = getBaselineGwp(product)
  const phaseRows =
    totalGwp != null ? allocateGwpByPhase(totalGwp, interp.hotspots, boundary) : []
  const displayRows = phaseRows.filter((r) => r.pct > 0)
  const phaseTotalKg = displayRows.length > 0 ? sumPhaseKg(displayRows) : null
  const maxPct = Math.max(...displayRows.map((r) => r.pct), 1)

  const body = `
<div class="cover">
  <div>
    <div class="cover-title">${s.title}</div>
    <div class="cover-product">${escapeHtml(product.name)}</div>
    <div class="cover-subtitle">${s.subtitle}</div>
    <table class="cover-meta-table">
      <tr><td>ISO 14067</td><td>${da ? "Produkt-CF (partial footprint)" : "Product CF (partial footprint)"}</td></tr>
      <tr><td>${s.boundary}</td><td>${escapeHtml(gs.systemBoundaries ?? "—")}</td></tr>
      <tr><td>${da ? "Dato" : "Date"}</td><td>${escapeHtml(date)}</td></tr>
      <tr><td>Document ID</td><td>#${escapeHtml(reportId)}</td></tr>
    </table>
  </div>
  <div class="cover-bottom">
    <div class="cover-highlights">
      ${totalGwp != null ? `
      <div class="hero-gwp">${totalGwp}</div>
      <div class="hero-unit">kg CO₂-eq ${s.perFu}</div>
      ` : ""}
    </div>
    ${buildCoverStamp(reportId)}
  </div>
</div>

<h2>${s.toc}</h2>
<table class="toc-table">
  <tr><td>1. ${s.s1}</td><td>2</td></tr>
  <tr><td>2. ${s.s2}</td><td>3</td></tr>
  <tr><td>3. ${s.s3}</td><td>4</td></tr>
  <tr><td>4. ${s.s4}</td><td>5</td></tr>
  <tr><td>5. ${s.s5}</td><td>6</td></tr>
  <tr><td>6. ${s.s6}</td><td>7</td></tr>
</table>

<div class="section"><h2>1. ${s.s1}</h2>
<div class="callout">${s.scopeBox}</div>
<h3>${s.notIncluded}</h3>
<p>${s.notIncludedList}</p>
</div>

<div class="section"><h2>2. ${s.s2}</h2>
<table>
<tr><th>${da ? "Parameter" : "Parameter"}</th><th>${da ? "Værdi" : "Value"}</th></tr>
<tr><td>${da ? "Funktionel enhed" : "Functional unit"}</td><td>${escapeHtml(gs.functionalUnit?.text ?? "—")}</td></tr>
<tr><td>${da ? "Referenceflow" : "Reference flow"}</td><td>${escapeHtml(gs.referenceFlow ?? "—")}</td></tr>
<tr><td>${s.boundary}</td><td>${escapeHtml(gs.systemBoundaries ?? "—")}</td></tr>
<tr><td>${s.period}</td><td>${escapeHtml(gs.timePeriod ?? "—")}</td></tr>
<tr><td>${da ? "Geografisk scope" : "Geographic scope"}</td><td>${escapeHtml(gs.geographicScope ?? "—")}</td></tr>
</table>
${gs.purpose ? `<p>${escapeHtml(gs.purpose)}</p>` : ""}
</div>

<div class="section"><h2>3. ${s.s3}</h2>
<p>${da ? "Eneste deklarerede indikator i denne ISO 14067-rapport:" : "The only declared indicator in this ISO 14067 report:"}</p>
${totalGwp != null ? `
<div class="hero-gwp">${totalGwp}</div>
<div class="hero-unit">kg CO₂-eq ${s.perFu}</div>
<table>
<tr><th>${da ? "Indikator" : "Indicator"}</th><th>${da ? "Værdi" : "Value"}</th><th>${da ? "Enhed" : "Unit"}</th></tr>
<tr><td>GWP100 (Climate change)</td><td class="num"><strong>${totalGwp}</strong></td><td>kg CO₂-eq / FU</td></tr>
</table>
` : `<p>—</p>`}
</div>

<div class="section"><h2>4. ${s.s4}</h2>
<p>${da ? "Fordeling af GWP på livscyklusfaser (fra hotspot-analyse)." : "GWP distribution across life cycle phases (from hotspot analysis)."}</p>
<table>
<tr><th>${s.phase}</th><th>${s.gwp} (kg CO₂-eq)</th><th>${s.share}</th><th></th></tr>
${displayRows
  .map((r) => {
    const barW = Math.round((r.pct / maxPct) * 100)
    return `<tr>
      <td>${escapeHtml(r.label[locale])}</td>
      <td class="num">${r.kg}</td>
      <td class="num">${r.pct}%</td>
      <td class="bar-cell"><span class="bar-fill" style="width:${barW}%"></span></td>
    </tr>`
  })
  .join("")}
<tr style="font-weight:bold"><td>${da ? "Total" : "Total"}</td><td class="num">${phaseTotalKg ?? totalGwp ?? "—"}</td><td class="num">100%</td><td></td></tr>
<p style="font-size:9pt;color:#555;margin-top:4pt;">${da ? "Faseandele er normaliseret fra hotspot-data, så kg summerer til det deklarerede GWP-tal." : "Phase shares are normalised from hotspot data so kg values sum to the declared GWP total."}</p>
</table>
${interp.hotspots?.length ? buildHotspotNarrative(interp.hotspots, locale) : ""}
</div>

<div class="section"><h2>5. ${s.s5}</h2>
<table>
<tr><th>${da ? "Emne" : "Topic"}</th><th>${da ? "Værdi" : "Value"}</th></tr>
<tr><td>${s.method}</td><td>${escapeHtml(lcia.method ?? "IPCC AR6 GWP100")}</td></tr>
<tr><td>${da ? "Biogent/karbon" : "Biogenic carbon"}</td><td>${da ? "Ikke separat rapporteret (prototype)" : "Not separately reported (prototype)"}</td></tr>
<tr><td>${s.compliance}</td><td>${product.complianceScore ?? "—"}%</td></tr>
<tr><td>${s.dataQuality}</td><td>${da ? "Baseret på produktets LCI-kilder og DQI" : "Based on product LCI sources and DQI"}</td></tr>
</table>
</div>

<div class="section"><h2>6. ${s.s6}</h2>
${interp.conclusions ? `<p><strong>${da ? "Fortolkning:" : "Interpretation:"}</strong> ${escapeHtml(interp.conclusions)}</p>` : ""}
${interp.limitations ? `<p><strong>${da ? "Begrænsninger:" : "Limitations:"}</strong> ${escapeHtml(interp.limitations)}</p>` : ""}
${gs.limitations ? `<p>${escapeHtml(gs.limitations)}</p>` : ""}
<p style="font-size:9pt;">${da ? "Fuld LCA med alle impact-kategorier: vælg ISO 14044 Full Report i eksport." : "Full LCA with all impact categories: choose ISO 14044 Full Report in export."}</p>
</div>
`

  return wrapReportHtml(locale, `PCF — ${product.name}`, body, s.generatedBy, reportId, date)
}

function buildHotspotNarrative(
  hotspots: { phase?: string; contribution?: number; driver?: string }[],
  locale: "da" | "en"
): string {
  const da = locale === "da"
  const items = hotspots
    .filter((h) => h.phase && h.contribution != null)
    .map(
      (h) =>
        `<li><strong>${escapeHtml(h.phase)}</strong>: ${h.contribution}% — ${escapeHtml(h.driver ?? "")}</li>`
    )
    .join("")
  if (!items) return ""
  return `<h3>${da ? "Væsentlige drivere" : "Key drivers"}</h3><ul>${items}</ul>`
}
