import type { ReportBuildInput } from "./shared"
import {
  allocateGwpByPhase,
  averageDqi,
  buildCoverStamp,
  detectSystemBoundary,
  escapeHtml,
  getBaselineGwp,
  wrapReportHtml,
} from "./shared"

const STRINGS = {
  da: {
    title: "Environmental Product Declaration",
    subtitle: "Miljøvaredeklaration — ISO 14025 + EN 15804+A2",
    generatedBy: "Genereret af LCA Compass",
    toc: "Indhold",
    s1: "Produktidentifikation",
    s2: "Program og PCR",
    s3: "LCA-resultater pr. modul (GWP)",
    s4: "Øvrige miljøindikatorer",
    s5: "Datakvalitet og verifikation",
    s6: "Forbehold og referencer",
    declaredUnit: "Deklareret enhed",
    referenceFlow: "Referenceflow",
    systemBoundary: "Systemgrænse",
    pcr: "PCR / produktkategori",
    validity: "Gyldighed",
    verifier: "Verifikationsniveau",
    totalGwp: "Samlet GWP (deklareret)",
    module: "Modul",
    gwp: "GWP",
    unit: "kg CO₂-eq",
    na: "ikke omfattet",
    gateNote: "Rapporten dækker cradle-to-gate (A1–A4). Moduler B og C er uden for deklarationen.",
    indicatorsNote: "EPD fokuserer på obligatoriske indikatorer. Øvrige LCIA-kategorier kan kræves i PCR.",
    prototype: "Prototype-EPD genereret i LCA Compass til demonstrationsformål.",
  },
  en: {
    title: "Environmental Product Declaration",
    subtitle: "Environmental declaration — ISO 14025 + EN 15804+A2",
    generatedBy: "Generated by LCA Compass",
    toc: "Contents",
    s1: "Product identification",
    s2: "Programme and PCR",
    s3: "LCA results per module (GWP)",
    s4: "Additional environmental indicators",
    s5: "Data quality and verification",
    s6: "Disclaimers and references",
    declaredUnit: "Declared unit",
    referenceFlow: "Reference flow",
    systemBoundary: "System boundary",
    pcr: "PCR / product category",
    validity: "Validity",
    verifier: "Verification level",
    totalGwp: "Total GWP (declared)",
    module: "Module",
    gwp: "GWP",
    unit: "kg CO₂-eq",
    na: "not included",
    gateNote: "This declaration covers cradle-to-gate (A1–A4). Modules B and C are outside the scope.",
    indicatorsNote: "The EPD focuses on mandatory indicators. Other LCIA categories may be required by the PCR.",
    prototype: "Prototype EPD generated in LCA Compass for demonstration purposes.",
  },
}

export function buildEpdIso14025Report(input: ReportBuildInput): string {
  const { product, locale, date, reportId, options } = input
  const s = STRINGS[locale]
  const da = locale === "da"
  const gs = product.goalScope ?? {}
  const lcia = product.lcia ?? {}
  const interp = product.interpretation ?? {}
  const boundary = detectSystemBoundary(gs.systemBoundaries)
  const totalGwp = getBaselineGwp(product)
  const phaseRows = totalGwp != null ? allocateGwpByPhase(totalGwp, interp.hotspots, boundary) : []
  const phaseMap = Object.fromEntries(phaseRows.map((r) => [r.phase, r.kg]))

  const moduleRows = buildModuleTable(phaseMap, boundary, locale)
  const avgDqi = options?.showDqi ? averageDqi(product.lci?.rawMaterial) : null
  const categories = (lcia.categories as string[] | undefined) ?? ["GWP"]
  const extraIndicators = categories.filter((c) => c !== "GWP" && c !== "gwp")

  const validityEnd = new Date()
  validityEnd.setFullYear(validityEnd.getFullYear() + 5)
  const validityStr = validityEnd.toLocaleDateString(da ? "da-DK" : "en-GB", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })

  const body = `
<div class="cover">
  <div>
    <div class="cover-title">${s.title}</div>
    <div class="cover-product">${escapeHtml(product.name)}</div>
    <div class="cover-subtitle">${s.subtitle}</div>
    <table class="cover-meta-table">
      <tr><td>${s.declaredUnit}</td><td>${escapeHtml(gs.functionalUnit?.text ?? "—")}</td></tr>
      <tr><td>${s.systemBoundary}</td><td>${escapeHtml(gs.systemBoundaries ?? "—")}</td></tr>
      <tr><td>${s.pcr}</td><td>${escapeHtml(guessPcr(product.productType, locale))}</td></tr>
      <tr><td>${s.validity}</td><td>${escapeHtml(date)} — ${escapeHtml(validityStr)}</td></tr>
      <tr><td>${s.verifier}</td><td>${da ? "EPD-verificeret (ambitionsniveau)" : "EPD verified (ambition level)"}</td></tr>
      <tr><td>Document ID</td><td>#${escapeHtml(reportId)}</td></tr>
    </table>
  </div>
  <div class="cover-bottom">
    <div class="cover-highlights">
      <div class="cover-highlights-title">${s.totalGwp}</div>
      ${totalGwp != null ? `<div class="cover-kpi"><div class="cover-kpi-value">${totalGwp} ${s.unit} / FU</div></div>` : ""}
      <p style="font-size:9pt;margin-top:6pt;">${s.prototype}</p>
    </div>
    ${buildCoverStamp(reportId)}
  </div>
</div>

<h2>${s.toc}</h2>
<table class="toc-table">
  <tr><td>1. ${s.s1}</td><td>2</td></tr>
  <tr><td>2. ${s.s2}</td><td>3</td></tr>
  <tr><td>3. ${s.s3}</td><td>4</td></tr>
  <tr><td>4. ${s.s4}</td><td>5</td></tr>
  <tr><td>5. ${s.s5}</td><td>6</td></tr>
  <tr><td>6. ${s.s6}</td><td>7</td></tr>
</table>

<div class="section"><h2>1. ${s.s1}</h2>
<table>
<tr><th>${da ? "Felt" : "Field"}</th><th>${da ? "Værdi" : "Value"}</th></tr>
<tr><td>${da ? "Produktnavn" : "Product name"}</td><td>${escapeHtml(product.name)}</td></tr>
<tr><td>${da ? "Produktkategori" : "Product category"}</td><td>${escapeHtml(product.productType ?? "—")}</td></tr>
<tr><td>${s.declaredUnit}</td><td>${escapeHtml(gs.functionalUnit?.text ?? "—")} (${gs.functionalUnit?.quantity ?? 1} ${escapeHtml(gs.functionalUnit?.unit ?? "")})</td></tr>
<tr><td>${s.referenceFlow}</td><td>${escapeHtml(gs.referenceFlow ?? "—")}</td></tr>
<tr><td>${da ? "Beskrivelse" : "Description"}</td><td>${escapeHtml(product.description ?? "—")}</td></tr>
<tr><td>${da ? "Geografisk scope" : "Geographic scope"}</td><td>${escapeHtml(gs.geographicScope ?? "—")}</td></tr>
<tr><td>${da ? "Tidsperiode" : "Time period"}</td><td>${escapeHtml(gs.timePeriod ?? "—")}</td></tr>
</table>
${gs.purpose ? `<p><strong>${da ? "Formål:" : "Purpose:"}</strong> ${escapeHtml(gs.purpose)}</p>` : ""}
</div>

<div class="section"><h2>2. ${s.s2}</h2>
<table>
<tr><th>${da ? "Parameter" : "Parameter"}</th><th>${da ? "Værdi" : "Value"}</th></tr>
<tr><td>${da ? "EPD-program" : "EPD programme"}</td><td>EPD Danmark / International EPD System (demo)</td></tr>
<tr><td>${s.pcr}</td><td>${escapeHtml(guessPcr(product.productType, locale))}</td></tr>
<tr><td>${da ? "LCIA-metode" : "LCIA method"}</td><td>${escapeHtml(lcia.method ?? "EN 15804+A2")}</td></tr>
<tr><td>${da ? "Allokering" : "Allocation"}</td><td>${escapeHtml(gs.allocationApproach ?? "—")}</td></tr>
<tr><td>${da ? "Cut-off" : "Cut-off"}</td><td>${gs.cutOffCriterion != null ? `${gs.cutOffCriterion}%` : "—"}</td></tr>
</table>
</div>

<div class="section"><h2>3. ${s.s3}</h2>
<p>${da ? "Klimapåvirkning (GWP100) fordelt på EN 15804-moduler. Tal er beregnet ud fra fase-hotspots i produktets LCA." : "Climate impact (GWP100) by EN 15804 module. Figures are allocated from phase hotspots in the product LCA."}</p>
${boundary === "cradle-to-gate" ? `<div class="callout callout-warn">${s.gateNote}</div>` : ""}
<table>
<tr><th>${s.module}</th><th>${da ? "Beskrivelse" : "Description"}</th><th>${s.gwp} (${s.unit})</th></tr>
${moduleRows}
<tr style="font-weight:bold;background:#e8e8e8"><td colspan="2">${da ? "Deklareret total (omfattet scope)" : "Declared total (in scope)"}</td><td class="num">${totalGwp ?? "—"}</td></tr>
</table>
</div>

<div class="section"><h2>4. ${s.s4}</h2>
<p>${s.indicatorsNote}</p>
<table>
<tr><th>${da ? "Indikator" : "Indicator"}</th><th>${da ? "Status i denne EPD" : "Status in this EPD"}</th></tr>
<tr><td>GWP (Climate change)</td><td class="num">${totalGwp ?? "—"} kg CO₂-eq / FU</td></tr>
${extraIndicators.map((ind) => `<tr><td>${escapeHtml(ind)}</td><td>${da ? "Angivet i LCIA — se fuld ISO 14044-rapport" : "In LCIA — see full ISO 14044 report"}</td></tr>`).join("")}
${lcia.results?.eWaste_kg ? `<tr><td>E-waste</td><td class="num">${lcia.results.eWaste_kg} kg / FU</td></tr>` : ""}
</table>
</div>

<div class="section"><h2>5. ${s.s5}</h2>
<table>
<tr><th>${da ? "Emne" : "Topic"}</th><th>${da ? "Vurdering" : "Assessment"}</th></tr>
<tr><td>${da ? "Ambitionsniveau" : "Ambition level"}</td><td>EPD_VERIFIED</td></tr>
<tr><td>${da ? "Gennemsnitlig DQI (1–5)" : "Average DQI (1–5)"}</td><td>${avgDqi ?? (da ? "Ikke vist" : "Not shown")}</td></tr>
<tr><td>ISO 14044 compliance</td><td>${product.complianceScore ?? "—"}%</td></tr>
</table>
${options?.showDqi && product.lci?.rawMaterial?.length ? buildDqiTable(product.lci.rawMaterial, locale) : ""}
</div>

<div class="section"><h2>6. ${s.s6}</h2>
${interp.conclusions ? `<p><strong>${da ? "Konklusion:" : "Conclusion:"}</strong> ${escapeHtml(interp.conclusions)}</p>` : ""}
${interp.limitations ? `<p><strong>${da ? "Begrænsninger:" : "Limitations:"}</strong> ${escapeHtml(interp.limitations)}</p>` : ""}
${gs.limitations ? `<p>${escapeHtml(gs.limitations)}</p>` : ""}
<p style="font-size:9pt;margin-top:8pt;">${s.prototype} ${da ? "Verificér dokument på lca-compass.dk med ID #" : "Verify at lca-compass.dk with ID #"}${escapeHtml(reportId)}</p>
</div>
`

  return wrapReportHtml(locale, `EPD — ${product.name}`, body, s.generatedBy, reportId, date)
}

function buildModuleTable(
  phaseMap: Record<string, number>,
  boundary: "cradle-to-gate" | "cradle-to-grave",
  locale: "da" | "en"
): string {
  const da = locale === "da"
  const na = da ? "ikke omfattet" : "not included"

  const rows: { id: string; desc: string; kg: number | null }[] = [
    {
      id: "A1",
      desc: da ? "Råmaterialer" : "Raw materials",
      kg: phaseMap.raw_material ?? null,
    },
    {
      id: "A2",
      desc: da ? "Transport til fabrik" : "Transport to factory",
      kg: null,
    },
    {
      id: "A3",
      desc: da ? "Produktion" : "Manufacturing",
      kg: phaseMap.production ?? null,
    },
    {
      id: "A4",
      desc: da ? "Transport til byggeplads/kunde" : "Transport to site/customer",
      kg: phaseMap.distribution ?? null,
    },
    {
      id: "A1-A3",
      desc: da ? "Produktion (sum)" : "Production stage (sum)",
      kg: sumNullable([phaseMap.raw_material, phaseMap.production]),
    },
    {
      id: "B",
      desc: da ? "Brug" : "Use",
      kg: boundary === "cradle-to-grave" ? (phaseMap.use ?? null) : null,
    },
    {
      id: "C",
      desc: da ? "End-of-life" : "End-of-life",
      kg: boundary === "cradle-to-grave" ? (phaseMap.end_of_life ?? null) : null,
    },
  ]

  return rows
    .map((r) => {
      const val =
        r.kg == null
          ? `<td class="na">${na}</td>`
          : `<td class="num">${Math.round(r.kg * 10) / 10}</td>`
      return `<tr><td><strong>${r.id}</strong></td><td>${escapeHtml(r.desc)}</td>${val}</tr>`
    })
    .join("")
}

function sumNullable(vals: (number | undefined)[]): number | null {
  const nums = vals.filter((v): v is number => typeof v === "number")
  if (!nums.length) return null
  return Math.round(nums.reduce((a, b) => a + b, 0) * 10) / 10
}

function guessPcr(productType: string | undefined, locale: "da" | "en"): string {
  const map: Record<string, { da: string; en: string }> = {
    CONSTRUCTION: { da: "PCR 2019:19 Byggevarer", en: "PCR 2019:19 Construction products" },
    ELECTRONICS: { da: "PCR EN 50693 Elektronik", en: "PCR EN 50693 Electronics" },
    TEXTILE: { da: "PCR tekstiler (demo)", en: "PCR textiles (demo)" },
    PACKAGING: { da: "PCR emballage", en: "PCR packaging" },
  }
  const entry = productType ? map[productType] : undefined
  return entry ? entry[locale] : locale === "da" ? "Generisk PCR (skal specificeres)" : "Generic PCR (to be specified)"
}

function buildDqiTable(
  materials: { name: string; dqi?: Record<string, number> }[],
  locale: "da" | "en"
): string {
  const da = locale === "da"
  return `<h3>${da ? "DQI pr. materiale" : "DQI per material"}</h3><table>
<tr><th>${da ? "Materiale" : "Material"}</th><th>R</th><th>C</th><th>T</th><th>G</th><th>Te</th></tr>
${materials
  .map((m) => {
    const d = m.dqi ?? {}
    return `<tr><td>${escapeHtml(m.name)}</td><td>${d.reliability ?? "—"}</td><td>${d.completeness ?? "—"}</td><td>${d.temporal ?? "—"}</td><td>${d.geographic ?? "—"}</td><td>${d.technological ?? "—"}</td></tr>`
  })
  .join("")}
</table>`
}
