import type { ReportBuildInput, ReportLocale } from "./shared"
import { limitationsToHtml } from "@/lib/lca/study-limitations"
import {
  buildCoverStamp,
  escapeHtml,
  hasAppendixContent,
  markdownToHtml,
  wrapReportHtml,
} from "./shared"

const STRINGS = {
  da: {
    title: "Livscyklusvurdering",
    subtitle: "Udarbejdet i overensstemmelse med ISO 14040:2006 og ISO 14044:2006",
    generatedBy: "Genereret af LCA Compass",
    tableOfContents: "Indholdsfortegnelse",
    executiveSummary: "Resumé",
    goalScope: "Formål og afgrænsning",
    lci: "Livscyklus-inventar",
    lcia: "Vurdering af miljøpåvirkning",
    interpretation: "Fortolkning",
    appendixA: "Bilag A — Detaljerede inventartabeller",
  },
  en: {
    title: "Life Cycle Assessment",
    subtitle: "Prepared in accordance with ISO 14040:2006 and ISO 14044:2006",
    generatedBy: "Generated by LCA Compass",
    tableOfContents: "Table of Contents",
    executiveSummary: "Executive Summary",
    goalScope: "Goal & Scope Definition",
    lci: "Life Cycle Inventory",
    lcia: "Life Cycle Impact Assessment",
    interpretation: "Interpretation",
    appendixA: "Appendix A — Detailed Inventory Tables",
  },
}

export function buildIso14044FullReport(input: ReportBuildInput): string {
  const { product, prose, locale, date, reportId, reportFormat, options } = input
  const strings = STRINGS[locale]
  const gs = product.goalScope ?? {}
  const lcia = product.lcia ?? {}
  const da = locale === "da"
  const showAppendix = Boolean(options?.includeAppendices && hasAppendixContent(product))

  const body = `
<div class="cover">
  <div>
    <div class="cover-title">${strings.title}</div>
    <div class="cover-product">${escapeHtml(product.name)}</div>
    <div class="cover-subtitle">${strings.subtitle}</div>
    <table class="cover-meta-table">
      <tr><td>${da ? "Rapporttype" : "Report type"}</td><td>${escapeHtml(reportFormat ?? "ISO_14044_FULL")}</td></tr>
      <tr><td>${da ? "Dato" : "Date"}</td><td>${escapeHtml(date)}</td></tr>
      <tr><td>${da ? "Sprog" : "Language"}</td><td>${da ? "Dansk" : "English"}</td></tr>
      <tr><td>ISO 14044 Compliance</td><td>${product.complianceScore ?? "—"}%</td></tr>
    </table>
  </div>
  <div class="cover-bottom">
    <div class="cover-highlights">
      <div class="cover-highlights-title">${da ? "Nøgletal" : "Key figures"}</div>
      ${lcia?.results?.gwp_kg_co2 ? `<div class="cover-kpi"><div class="cover-kpi-label">GWP100</div><div class="cover-kpi-value">${lcia.results.gwp_kg_co2} kg CO₂-eq / FU</div></div>` : ""}
      ${gs?.systemBoundaries ? `<div class="cover-kpi"><div class="cover-kpi-label">${da ? "Systemgrænse" : "System boundary"}</div><div class="cover-kpi-value">${escapeHtml(gs.systemBoundaries)}</div></div>` : ""}
    </div>
    ${buildCoverStamp(reportId)}
  </div>
</div>

<h2>${strings.tableOfContents}</h2>
<table class="toc-table">
  <tr><td>1. ${strings.executiveSummary}</td><td>2</td></tr>
  <tr><td>2. ${strings.goalScope}</td><td>3</td></tr>
  <tr><td>3. ${strings.lci}</td><td>5</td></tr>
  <tr><td>4. ${strings.lcia}</td><td>8</td></tr>
  <tr><td>5. ${strings.interpretation}</td><td>11</td></tr>
  ${showAppendix ? `<tr><td>${strings.appendixA}</td><td>14</td></tr>` : ""}
</table>

<div class="section"><h2>1. ${strings.executiveSummary}</h2>
${markdownToHtml(prose.executive_summary ?? "")}
${lcia?.results?.gwp_kg_co2 ? `<div class="callout"><strong>${da ? "Nøgleresultat:" : "Key result:"}</strong> GWP = <strong>${lcia.results.gwp_kg_co2} kg CO₂-eq</strong> / FU</div>` : ""}
</div>

<div class="section"><h2>2. ${strings.goalScope}</h2>
${markdownToHtml(prose.goal_scope ?? "")}
${gs.functionalUnit ? `<table>
<tr><th>${da ? "Parameter" : "Parameter"}</th><th>${da ? "Værdi" : "Value"}</th></tr>
<tr><td>${da ? "Funktionel enhed" : "Functional unit"}</td><td>${escapeHtml(gs.functionalUnit.text)}</td></tr>
<tr><td>${da ? "Systemgrænse" : "System boundary"}</td><td>${escapeHtml(gs.systemBoundaries ?? "—")}</td></tr>
</table>` : ""}
</div>

<div class="section"><h2>3. ${strings.lci}</h2>${markdownToHtml(prose.lci_raw ?? "")}${buildRawMaterialTable(product, locale)}</div>
<div class="section"><h2>4. ${strings.lcia}</h2>${markdownToHtml(prose.lcia ?? "")}${buildImpactTable(product, locale)}</div>
<div class="section"><h2>5. ${strings.interpretation}</h2>${markdownToHtml(prose.interpretation ?? "")}${limitationsToHtml(locale, product)}</div>
${showAppendix ? `<div class="section"><h2>${strings.appendixA}</h2>${buildAppendix(product, locale, Boolean(options?.showDqi))}</div>` : ""}
`

  return wrapReportHtml(locale, `${strings.title} — ${product.name}`, body, strings.generatedBy, reportId, date)
}

function buildRawMaterialTable(product: { lci?: { rawMaterial?: unknown[] } }, locale: ReportLocale): string {
  const materials = product.lci?.rawMaterial as
    | { name: string; quantity: number; unit: string; sourceType: string; dqi?: Record<string, number> }[]
    | undefined
  if (!materials?.length) return ""
  const da = locale === "da"
  return `<h3>${da ? "Råmaterialer" : "Raw materials"}</h3><table>
<tr><th>${da ? "Materiale" : "Material"}</th><th>${da ? "Mængde" : "Qty"}</th><th>${da ? "Enhed" : "Unit"}</th><th>${da ? "Kilde" : "Source"}</th><th>DQI</th></tr>
${materials
  .map((m) => {
    const d = m.dqi
    const dqi = d
      ? Math.round(
          (((d.reliability ?? 0) +
            (d.completeness ?? 0) +
            (d.temporal ?? 0) +
            (d.geographic ?? 0) +
            (d.technological ?? 0)) /
            5) *
            10
        ) / 10
      : "—"
    return `<tr><td>${escapeHtml(m.name)}</td><td>${m.quantity ?? "—"}</td><td>${escapeHtml(m.unit)}</td><td>${escapeHtml(m.sourceType)}</td><td>${dqi}</td></tr>`
  })
  .join("")}
</table>`
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function buildAppendix(product: any, locale: ReportLocale, showDqi: boolean): string {
  const da = locale === "da"
  const lci = product.lci ?? {}
  const interp = product.interpretation ?? {}
  const parts: string[] = []

  parts.push(`<p>${da ? "Detaljerede livscyklusinventardata og datakvalitetsvurdering (DQI) for dette studie." : "Detailed life cycle inventory data and data quality assessment (DQI) for this study."}</p>`)

  const materials = lci.rawMaterial as
    | {
        name: string
        quantity?: number
        unit?: string
        sourceType?: string
        sourceDetails?: string
        co2eqPerUnit?: number
        dqi?: Record<string, number>
      }[]
    | undefined

  if (materials?.length) {
    parts.push(`<h3>${da ? "Bilag A.1 — Råmaterialer" : "Appendix A.1 — Raw materials"}</h3><table>
<tr><th>${da ? "Materiale" : "Material"}</th><th>${da ? "Mængde" : "Qty"}</th><th>${da ? "Enhed" : "Unit"}</th><th>${da ? "Kilde" : "Source"}</th><th>kg CO₂-eq/${da ? "enhed" : "unit"}</th></tr>
${materials
  .map(
    (m) => `<tr><td>${escapeHtml(m.name)}</td><td class="num">${m.quantity ?? "—"}</td><td>${escapeHtml(m.unit ?? "")}</td><td>${escapeHtml(m.sourceType ?? "")} — ${escapeHtml(m.sourceDetails ?? "")}</td><td class="num">${m.co2eqPerUnit ?? "—"}</td></tr>`
  )
  .join("")}
</table>`)
  }

  if (showDqi && materials?.length) {
    parts.push(`<h3>${da ? "Bilag A.2 — Pedigree matrix (DQI 1–5)" : "Appendix A.2 — Pedigree matrix (DQI 1–5)"}</h3>
<p style="font-size:9pt;">${da ? "R = pålidelighed, C = fuldstændighed, T = temporal, G = geografisk, Te = teknologisk (ISO 14044 §4.2.3.6.2)." : "R = reliability, C = completeness, T = temporal, G = geographic, Te = technological (ISO 14044 §4.2.3.6.2)."}</p>
<table>
<tr><th>${da ? "Materiale" : "Material"}</th><th>R</th><th>C</th><th>T</th><th>G</th><th>Te</th><th>${da ? "Gns." : "Avg."}</th></tr>
${materials
  .map((m) => {
    const d = m.dqi ?? {}
    const scores = [d.reliability, d.completeness, d.temporal, d.geographic, d.technological].filter(
      (v) => typeof v === "number"
    ) as number[]
    const avg = scores.length
      ? Math.round((scores.reduce((a, b) => a + b, 0) / scores.length) * 10) / 10
      : "—"
    return `<tr><td>${escapeHtml(m.name)}</td><td>${d.reliability ?? "—"}</td><td>${d.completeness ?? "—"}</td><td>${d.temporal ?? "—"}</td><td>${d.geographic ?? "—"}</td><td>${d.technological ?? "—"}</td><td class="num">${avg}</td></tr>`
  })
  .join("")}
</table>`)
  }

  const dist = lci.distribution as { from?: string; to?: string; distance?: number; method?: string }[] | undefined
  if (dist?.length) {
    parts.push(`<h3>${da ? "Bilag A.3 — Transport" : "Appendix A.3 — Transport"}</h3><table>
<tr><th>${da ? "Fra" : "From"}</th><th>${da ? "Til" : "To"}</th><th>${da ? "Afstand" : "Distance"}</th><th>${da ? "Metode" : "Mode"}</th></tr>
${dist.map((d) => `<tr><td>${escapeHtml(d.from)}</td><td>${escapeHtml(d.to)}</td><td class="num">${d.distance ?? "—"} km</td><td>${escapeHtml(d.method ?? "")}</td></tr>`).join("")}
</table>`)
  }

  const sens = interp.sensitivityAnalysis as { parameters?: string[]; results?: string } | undefined
  if (sens?.parameters?.length || sens?.results) {
    parts.push(`<h3>${da ? "Bilag A.4 — Sensitivitetsanalyse" : "Appendix A.4 — Sensitivity analysis"}</h3>`)
    if (sens.parameters?.length) {
      parts.push(`<p><strong>${da ? "Parametre:" : "Parameters:"}</strong> ${escapeHtml(sens.parameters.join(", "))}</p>`)
    }
    if (sens.results) parts.push(`<p>${escapeHtml(sens.results)}</p>`)
  }

  if (parts.length === 1) {
    parts.push(`<p>${da ? "Ingen detaljerede inventardata registreret for dette produkt." : "No detailed inventory data recorded for this product."}</p>`)
  }

  return parts.join("\n")
}

function buildImpactTable(product: { lcia?: { results?: Record<string, unknown>; method?: string } }, locale: ReportLocale): string {
  const lcia = product.lcia
  if (!lcia?.results) return ""
  const da = locale === "da"
  return `<h3>${da ? "Resultater" : "Results"}</h3><table>
<tr><th>${da ? "Impact-kategori" : "Impact category"}</th><th>${da ? "Resultat" : "Result"}</th><th>${da ? "Enhed" : "Unit"}</th></tr>
<tr><td>Climate change (GWP100)</td><td class="num">${lcia.results.gwp_kg_co2}</td><td>kg CO₂-eq / FU</td></tr>
${lcia.results.eWaste_kg ? `<tr><td>E-waste</td><td class="num">${lcia.results.eWaste_kg}</td><td>kg / FU</td></tr>` : ""}
</table>`
}
